Set wshShell =wscript.CreateObject("WScript.Shell")
dim result

do
wshshell.sendkeys "{NUMLOCK}"
wscript.sleep 200
wshshell.sendkeys "{NUMLOCK}"
wshshell.sendkeys "{CAPSLOCK}"
wscript.sleep 200
wshshell.sendkeys "{CAPSLOCK}"
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 200
wshshell.sendkeys "{SCROLLLOCK}"
wshshell.sendkeys "{NUMLOCK}"
wscript.sleep 200
wshshell.sendkeys "{NUMLOCK}"
wshshell.sendkeys "{CAPSLOCK}"
wscript.sleep 200
wshshell.sendkeys "{CAPSLOCK}"
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 200
wshshell.sendkeys "{SCROLLLOCK}"
wshshell.sendkeys "{NUMLOCK}"
wscript.sleep 200
wshshell.sendkeys "{NUMLOCK}"
wshshell.sendkeys "{CAPSLOCK}"
wscript.sleep 200
wshshell.sendkeys "{CAPSLOCK}"
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 200
wshshell.sendkeys "{SCROLLLOCK}"
wshshell.sendkeys "{NUMLOCK}"
wscript.sleep 200
wshshell.sendkeys "{NUMLOCK}"
wshshell.sendkeys "{CAPSLOCK}"
wscript.sleep 200
wshshell.sendkeys "{CAPSLOCK}"
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 200
wshshell.sendkeys "{SCROLLLOCK}"
wshshell.sendkeys "{NUMLOCK}"
wscript.sleep 200
wshshell.sendkeys "{NUMLOCK}"
wshshell.sendkeys "{CAPSLOCK}"
wscript.sleep 200
wshshell.sendkeys "{CAPSLOCK}"
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 200
wshshell.sendkeys "{SCROLLLOCK}"

wscript.sleep 500

wshshell.sendkeys "{CAPSLOCK}"
wscript.sleep 100
wshshell.sendkeys "{NUMLOCK}"
wscript.sleep 50
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 50
wshshell.sendkeys "{CAPSLOCK}"
wscript.sleep 100
wshshell.sendkeys "{NUMLOCK}"
wscript.sleep 50
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 50
wshshell.sendkeys "{CAPSLOCK}"
wscript.sleep 100
wshshell.sendkeys "{NUMLOCK}"
wscript.sleep 50
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 50
wshshell.sendkeys "{CAPSLOCK}"
wscript.sleep 100
wshshell.sendkeys "{NUMLOCK}"
wscript.sleep 50
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 50
wshshell.sendkeys "{CAPSLOCK}"
wscript.sleep 100
wshshell.sendkeys "{NUMLOCK}"
wscript.sleep 50
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 50
wshshell.sendkeys "{CAPSLOCK}"
wscript.sleep 100
wshshell.sendkeys "{NUMLOCK}"
wscript.sleep 50
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 50
wshshell.sendkeys "{CAPSLOCK}"
wscript.sleep 100
wshshell.sendkeys "{NUMLOCK}"
wscript.sleep 50
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 50
wshshell.sendkeys "{CAPSLOCK}"
wscript.sleep 100
wshshell.sendkeys "{NUMLOCK}"
wscript.sleep 50
wshshell.sendkeys "{SCROLLLOCK}"

wscript.sleep 500

wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 200
wshshell.sendkeys "{SCROLLLOCK}"
wshshell.sendkeys "{CAPSLOCK}"
wscript.sleep 200
wshshell.sendkeys "{CAPSLOCK}"
wshshell.sendkeys "{NUMLOCK}"
wscript.sleep 200
wshshell.sendkeys "{NUMLOCK}"
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 200
wshshell.sendkeys "{SCROLLLOCK}"
wshshell.sendkeys "{CAPSLOCK}"
wscript.sleep 200
wshshell.sendkeys "{CAPSLOCK}"
wshshell.sendkeys "{NUMLOCK}"
wscript.sleep 200
wshshell.sendkeys "{NUMLOCK}"
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 200
wshshell.sendkeys "{SCROLLLOCK}"
wshshell.sendkeys "{CAPSLOCK}"
wscript.sleep 200
wshshell.sendkeys "{CAPSLOCK}"
wshshell.sendkeys "{NUMLOCK}"
wscript.sleep 200
wshshell.sendkeys "{NUMLOCK}"
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 200
wshshell.sendkeys "{SCROLLLOCK}"
wshshell.sendkeys "{CAPSLOCK}"
wscript.sleep 200
wshshell.sendkeys "{CAPSLOCK}"
wshshell.sendkeys "{NUMLOCK}"
wscript.sleep 200
wshshell.sendkeys "{NUMLOCK}"
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 200
wshshell.sendkeys "{SCROLLLOCK}"
wshshell.sendkeys "{CAPSLOCK}"
wscript.sleep 200
wshshell.sendkeys "{CAPSLOCK}"
wshshell.sendkeys "{NUMLOCK}"
wscript.sleep 200
wshshell.sendkeys "{NUMLOCK}"

wscript.sleep 500
loop